### ISSUE TITLE
Evaluate Math expressions does not accept mixed number formats/units

### ISSUE THREAD

**Issue by jens1o** [emmetio/math-expression#1]
Steps to Reproduce:

1. Having this:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        body {
            background-attachment: fixed;
            background-color: #000f + 23;
        }
    </style>
</head>
<body>
    
</body>
</html>
```
2. Select the hex code and the number: 
![image](https://user-images.githubusercontent.com/11234139/28733897-7f250930-73de-11e7-8274-b9ca65071c62.png)
3. Let the emmet extension fail silently... "Emmet: Evaluate Math Expression".
4. See it does not replace it with `38` (`#000f + 23 = 15 + 23` = `38`) nor with `#26` or `#000026`.

Original issue: https://github.com/Microsoft/vscode/issues/31681

**Comment by ramya-rao-a** [comment]
@sergeche The `@emmetio/math-expression` module does not support hex codes and so the above feature request. What's your thought on supporting this?

**Comment by sergeche** [comment]
Not sure if it’s a good and obvious idea to perform hex calculations in this context. Although it’s generally a good idea to perform some color math as in preprocessors. I can re-used my code from LiveStyle project to perform some advanced preprocessor-style color manipulations like `darken(#fc0, 0.1)`, `#111 + #222 → #333` etc.

**Comment by ramya-rao-a** [comment]
Agreed, also you currently support evaluating numbers that are preceded by text like `foo123`. It will be ambiguous to determine when the text preceding a number should be considered part of the hex and when not.

@jens1o Coming back to your original ask, I would say that it the `darken`/`lighten` feature would be a good extension candidate for VS Code.

**Comment by jens1o** [comment]
That's a good idea @ramya-rao-a :)

**Comment by ramya-rao-a** [comment]
Closing this issue then.

**Comment by jens1o** [comment]
sure. Thanks for the heads up! :)
