### ISSUE TITLE
Package does not work with newest scanner

### ISSUE THREAD

**Issue by rzhao271** [emmetio/math-expression#11]
Using `@emmetio/scanner@1.0.0`, this package builds, but using `@emmetio/scanner@1.0.2`, building this package results in an error saying it cannot find `scanner.cjs`.

This issue is blocking the VS Code team from adopting the latest Emmet: https://github.com/microsoft/vscode/pull/180583.

**Comment by rzhao271** [comment]
Hi @sergeche, please take a look at this issue and PR #13 when you have some time. Thanks

**Comment by sergeche** [comment]
Hi @rzhao271, thanks, published as patched versions:

 - @emmetio/abbreviation@2.3.2
 - @emmetio/css-abbreviation@2.1.7
 - @emmetio/scanner@1.0.3
 - emmet@2.4.3

**Comment by rzhao271** [comment]
`emmet@2.4.3` now builds nicely with `math-expression@1.0.4`, but when I try testing the upgraded Emmet extension, it fails to load, with a notification saying that it cannot find module `c:\<my-work-dir>\vscode\extensions\emmet\node_modules\@emmetio\math-expression\node_modules\@emmetio\scanner\scanner.cjs`. I think that math-expression still needs to either be updated (PR #13), or have its dependency on `@emmetio/scanner` frozen to version `1.0.0` (PR #12).

**Comment by sergeche** [comment]
Hi @rzhao271, just published `math-expression@1.0.5`, should fix the issue

**Comment by rzhao271** [comment]
Thanks! It does fix the issue
